// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_state.sql

package sqlcgen

import (
	"context"
)

const getAppState = `-- name: GetAppState :one
SELECT value FROM app_state WHERE key = ?
`

func (q *Queries) GetAppState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setAppState = `-- name: SetAppState :exec
INSERT INTO app_state (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetAppStateParams struct {
	Key   string
	Value string
}

func (q *Queries) SetAppState(ctx context.Context, arg SetAppStateParams) error {
	_, err := q.db.ExecContext(ctx, setAppState, arg.Key, arg.Value)
	return err
}
