// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const categoryExpenseCount = `-- name: CategoryExpenseCount :one
SELECT COUNT(*) FROM expenses WHERE category_id = ? AND deleted_at IS NULL
`

// Counts active (non-trashed) expenses only.
func (q *Queries) CategoryExpenseCount(ctx context.Context, categoryID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, categoryExpenseCount, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, color, icon, created_at, is_archived)
VALUES (?, ?, ?, ?, 0)
RETURNING id
`

type CreateCategoryParams struct {
	Name      string
	Color     string
	Icon      sql.NullString
	CreatedAt int64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, color, icon, created_at, is_archived
FROM categories
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.IsArchived,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, color, icon, created_at, is_archived
FROM categories
WHERE is_archived = 0
ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListActiveCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name, color, icon, created_at, is_archived
FROM categories
ORDER BY is_archived, name COLLATE NOCASE
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryArchived = `-- name: SetCategoryArchived :exec
UPDATE categories
SET is_archived = ?
WHERE id = ?
`

type SetCategoryArchivedParams struct {
	IsArchived int64
	ID         int64
}

func (q *Queries) SetCategoryArchived(ctx context.Context, arg SetCategoryArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setCategoryArchived, arg.IsArchived, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET name = ?, color = ?, icon = ?
WHERE id = ?
`

type UpdateCategoryParams struct {
	Name  string
	Color string
	Icon  sql.NullString
	ID    int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.ID,
	)
	return err
}
