// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countDeletedExpenses = `-- name: CountDeletedExpenses :one
SELECT CAST(COUNT(*) AS INTEGER) FROM expenses WHERE deleted_at IS NOT NULL
`

func (q *Queries) CountDeletedExpenses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeletedExpenses)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (amount, description, notes, spent_at, category_id, ledger_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateExpenseParams struct {
	Amount      int64
	Description string
	Notes       sql.NullString
	SpentAt     int64
	CategoryID  sql.NullInt64
	LedgerID    sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.Amount,
		arg.Description,
		arg.Notes,
		arg.SpentAt,
		arg.CategoryID,
		arg.LedgerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const dailySpendingBetween = `-- name: DailySpendingBetween :many
SELECT
    CAST(strftime('%s', date(spent_at, 'unixepoch')) AS INTEGER) AS day,
    CAST(COALESCE(SUM(amount), 0) AS INTEGER)                    AS total
FROM expenses
WHERE spent_at >= ? AND spent_at < ? AND deleted_at IS NULL
GROUP BY day
ORDER BY day
`

type DailySpendingBetweenParams struct {
	SpentAt   int64
	SpentAt_2 int64
}

type DailySpendingBetweenRow struct {
	Day   int64
	Total int64
}

func (q *Queries) DailySpendingBetween(ctx context.Context, arg DailySpendingBetweenParams) ([]DailySpendingBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, dailySpendingBetween, arg.SpentAt, arg.SpentAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySpendingBetweenRow{}
	for rows.Next() {
		var i DailySpendingBetweenRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailySpendingForLedger = `-- name: DailySpendingForLedger :many
SELECT
    CAST(strftime('%s', date(spent_at, 'unixepoch')) AS INTEGER) AS day,
    CAST(COALESCE(SUM(amount), 0) AS INTEGER)                    AS total
FROM expenses
WHERE ledger_id = ? AND deleted_at IS NULL
GROUP BY day
ORDER BY day
`

type DailySpendingForLedgerRow struct {
	Day   int64
	Total int64
}

func (q *Queries) DailySpendingForLedger(ctx context.Context, ledgerID sql.NullInt64) ([]DailySpendingForLedgerRow, error) {
	rows, err := q.db.QueryContext(ctx, dailySpendingForLedger, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySpendingForLedgerRow{}
	for rows.Next() {
		var i DailySpendingForLedgerRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const emptyTrash = `-- name: EmptyTrash :execrows
DELETE FROM expenses WHERE deleted_at IS NOT NULL
`

// Hard-deletes every currently soft-deleted row.
func (q *Queries) EmptyTrash(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, emptyTrash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeletedExpense = `-- name: GetDeletedExpense :one
SELECT id, amount, description, notes, spent_at, category_id, ledger_id, created_at, updated_at, deleted_at
FROM expenses
WHERE id = ?
`

// Trash-only fetch: returns the row regardless of state, used by Restore /
// HardDelete handlers that need to read a soft-deleted row.
func (q *Queries) GetDeletedExpense(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getDeletedExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.Notes,
		&i.SpentAt,
		&i.CategoryID,
		&i.LedgerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpense = `-- name: GetExpense :one
SELECT id, amount, description, notes, spent_at, category_id, ledger_id, created_at, updated_at, deleted_at
FROM expenses
WHERE id = ? AND deleted_at IS NULL
`

// Returns only active rows. Trash UI uses GetDeletedExpense for the trash side.
func (q *Queries) GetExpense(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.Notes,
		&i.SpentAt,
		&i.CategoryID,
		&i.LedgerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteExpense = `-- name: HardDeleteExpense :exec
DELETE FROM expenses WHERE id = ? AND deleted_at IS NOT NULL
`

// Permanent delete. Used by the trash UI's "Delete forever" and by the
// maintenance sweeper. Restricted to already-trashed rows so a stray call
// can't bypass the trash.
func (q *Queries) HardDeleteExpense(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteExpense, id)
	return err
}

const listDeletedExpenses = `-- name: ListDeletedExpenses :many
SELECT
    e.id, e.amount, e.description, e.notes, e.spent_at,
    e.category_id, e.ledger_id, e.created_at, e.updated_at, e.deleted_at,
    c.name AS category_name, c.color AS category_color,
    l.name AS ledger_name
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
LEFT JOIN ledgers    l ON l.id = e.ledger_id
WHERE e.deleted_at IS NOT NULL
ORDER BY e.deleted_at DESC, e.id DESC
LIMIT ? OFFSET ?
`

type ListDeletedExpensesParams struct {
	Limit  int64
	Offset int64
}

type ListDeletedExpensesRow struct {
	ID            int64
	Amount        int64
	Description   string
	Notes         sql.NullString
	SpentAt       int64
	CategoryID    sql.NullInt64
	LedgerID      sql.NullInt64
	CreatedAt     int64
	UpdatedAt     int64
	DeletedAt     sql.NullInt64
	CategoryName  sql.NullString
	CategoryColor sql.NullString
	LedgerName    sql.NullString
}

// Trash listing, newest-deleted first.
func (q *Queries) ListDeletedExpenses(ctx context.Context, arg ListDeletedExpensesParams) ([]ListDeletedExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedExpenses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedExpensesRow{}
	for rows.Next() {
		var i ListDeletedExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.Notes,
			&i.SpentAt,
			&i.CategoryID,
			&i.LedgerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.LedgerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByLedger = `-- name: ListExpensesByLedger :many
SELECT
    e.id, e.amount, e.description, e.notes, e.spent_at,
    e.category_id, e.ledger_id, e.created_at, e.updated_at,
    c.name AS category_name, c.color AS category_color
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.ledger_id = ? AND e.deleted_at IS NULL
ORDER BY e.spent_at DESC, e.id DESC
`

type ListExpensesByLedgerRow struct {
	ID            int64
	Amount        int64
	Description   string
	Notes         sql.NullString
	SpentAt       int64
	CategoryID    sql.NullInt64
	LedgerID      sql.NullInt64
	CreatedAt     int64
	UpdatedAt     int64
	CategoryName  sql.NullString
	CategoryColor sql.NullString
}

func (q *Queries) ListExpensesByLedger(ctx context.Context, ledgerID sql.NullInt64) ([]ListExpensesByLedgerRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByLedger, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesByLedgerRow{}
	for rows.Next() {
		var i ListExpensesByLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.Notes,
			&i.SpentAt,
			&i.CategoryID,
			&i.LedgerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentExpenses = `-- name: ListRecentExpenses :many
SELECT
    e.id, e.amount, e.description, e.notes, e.spent_at,
    e.category_id, e.ledger_id, e.created_at, e.updated_at,
    c.name AS category_name, c.color AS category_color,
    l.name AS ledger_name
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
LEFT JOIN ledgers    l ON l.id = e.ledger_id
WHERE e.deleted_at IS NULL
ORDER BY e.spent_at DESC, e.id DESC
LIMIT ?
`

type ListRecentExpensesRow struct {
	ID            int64
	Amount        int64
	Description   string
	Notes         sql.NullString
	SpentAt       int64
	CategoryID    sql.NullInt64
	LedgerID      sql.NullInt64
	CreatedAt     int64
	UpdatedAt     int64
	CategoryName  sql.NullString
	CategoryColor sql.NullString
	LedgerName    sql.NullString
}

func (q *Queries) ListRecentExpenses(ctx context.Context, limit int64) ([]ListRecentExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentExpenses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentExpensesRow{}
	for rows.Next() {
		var i ListRecentExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.Notes,
			&i.SpentAt,
			&i.CategoryID,
			&i.LedgerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.LedgerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldDeletedExpenses = `-- name: PurgeOldDeletedExpenses :execrows
DELETE FROM expenses WHERE deleted_at IS NOT NULL AND deleted_at < ?
`

// Hard-deletes any soft-deleted rows older than the cutoff. Backs the
// trash sweeper.
func (q *Queries) PurgeOldDeletedExpenses(ctx context.Context, deletedAt sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldDeletedExpenses, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreExpense = `-- name: RestoreExpense :exec
UPDATE expenses SET deleted_at = NULL, updated_at = ? WHERE id = ? AND deleted_at IS NOT NULL
`

type RestoreExpenseParams struct {
	UpdatedAt int64
	ID        int64
}

// Brings a trashed row back. No-op for active rows.
func (q *Queries) RestoreExpense(ctx context.Context, arg RestoreExpenseParams) error {
	_, err := q.db.ExecContext(ctx, restoreExpense, arg.UpdatedAt, arg.ID)
	return err
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteExpenseParams struct {
	DeletedAt sql.NullInt64
	UpdatedAt int64
	ID        int64
}

// Moves the row to trash. Idempotent: deleting an already-deleted row is a no-op.
func (q *Queries) SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteExpense, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const spendingByCategoryBetween = `-- name: SpendingByCategoryBetween :many
SELECT
    e.category_id,
    COALESCE(c.name, 'Uncategorized')          AS category_name,
    COALESCE(c.color, '#6b7280')               AS category_color,
    CAST(COALESCE(SUM(e.amount), 0) AS INTEGER) AS total
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.spent_at >= ? AND e.spent_at < ? AND e.deleted_at IS NULL
GROUP BY e.category_id
ORDER BY total DESC
`

type SpendingByCategoryBetweenParams struct {
	SpentAt   int64
	SpentAt_2 int64
}

type SpendingByCategoryBetweenRow struct {
	CategoryID    sql.NullInt64
	CategoryName  string
	CategoryColor string
	Total         int64
}

func (q *Queries) SpendingByCategoryBetween(ctx context.Context, arg SpendingByCategoryBetweenParams) ([]SpendingByCategoryBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, spendingByCategoryBetween, arg.SpentAt, arg.SpentAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendingByCategoryBetweenRow{}
	for rows.Next() {
		var i SpendingByCategoryBetweenRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendingByCategoryForLedger = `-- name: SpendingByCategoryForLedger :many
SELECT
    e.category_id,
    COALESCE(c.name, 'Uncategorized')          AS category_name,
    COALESCE(c.color, '#6b7280')               AS category_color,
    CAST(COALESCE(SUM(e.amount), 0) AS INTEGER) AS total
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.ledger_id = ? AND e.deleted_at IS NULL
GROUP BY e.category_id
ORDER BY total DESC
`

type SpendingByCategoryForLedgerRow struct {
	CategoryID    sql.NullInt64
	CategoryName  string
	CategoryColor string
	Total         int64
}

func (q *Queries) SpendingByCategoryForLedger(ctx context.Context, ledgerID sql.NullInt64) ([]SpendingByCategoryForLedgerRow, error) {
	rows, err := q.db.QueryContext(ctx, spendingByCategoryForLedger, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendingByCategoryForLedgerRow{}
	for rows.Next() {
		var i SpendingByCategoryForLedgerRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendingByLedgerBetween = `-- name: SpendingByLedgerBetween :many
SELECT
    e.ledger_id,
    COALESCE(l.name, 'No ledger')              AS ledger_name,
    CAST(COALESCE(SUM(e.amount), 0) AS INTEGER) AS total
FROM expenses e
LEFT JOIN ledgers l ON l.id = e.ledger_id
WHERE e.spent_at >= ? AND e.spent_at < ? AND e.deleted_at IS NULL
GROUP BY e.ledger_id
ORDER BY total DESC
`

type SpendingByLedgerBetweenParams struct {
	SpentAt   int64
	SpentAt_2 int64
}

type SpendingByLedgerBetweenRow struct {
	LedgerID   sql.NullInt64
	LedgerName string
	Total      int64
}

func (q *Queries) SpendingByLedgerBetween(ctx context.Context, arg SpendingByLedgerBetweenParams) ([]SpendingByLedgerBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, spendingByLedgerBetween, arg.SpentAt, arg.SpentAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendingByLedgerBetweenRow{}
	for rows.Next() {
		var i SpendingByLedgerBetweenRow
		if err := rows.Scan(&i.LedgerID, &i.LedgerName, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryBetween = `-- name: SummaryBetween :one
SELECT
    CAST(COALESCE(SUM(amount), 0) AS INTEGER) AS total,
    CAST(COUNT(*) AS INTEGER)                  AS expense_count
FROM expenses
WHERE spent_at >= ? AND spent_at < ? AND deleted_at IS NULL
`

type SummaryBetweenParams struct {
	SpentAt   int64
	SpentAt_2 int64
}

type SummaryBetweenRow struct {
	Total        int64
	ExpenseCount int64
}

func (q *Queries) SummaryBetween(ctx context.Context, arg SummaryBetweenParams) (SummaryBetweenRow, error) {
	row := q.db.QueryRowContext(ctx, summaryBetween, arg.SpentAt, arg.SpentAt_2)
	var i SummaryBetweenRow
	err := row.Scan(&i.Total, &i.ExpenseCount)
	return i, err
}

const topExpensesBetween = `-- name: TopExpensesBetween :many
SELECT
    e.id, e.amount, e.description, e.spent_at,
    c.name AS category_name, c.color AS category_color,
    l.name AS ledger_name
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
LEFT JOIN ledgers    l ON l.id = e.ledger_id
WHERE e.spent_at >= ? AND e.spent_at < ? AND e.deleted_at IS NULL
ORDER BY e.amount DESC
LIMIT ?
`

type TopExpensesBetweenParams struct {
	SpentAt   int64
	SpentAt_2 int64
	Limit     int64
}

type TopExpensesBetweenRow struct {
	ID            int64
	Amount        int64
	Description   string
	SpentAt       int64
	CategoryName  sql.NullString
	CategoryColor sql.NullString
	LedgerName    sql.NullString
}

func (q *Queries) TopExpensesBetween(ctx context.Context, arg TopExpensesBetweenParams) ([]TopExpensesBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, topExpensesBetween, arg.SpentAt, arg.SpentAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopExpensesBetweenRow{}
	for rows.Next() {
		var i TopExpensesBetweenRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.SpentAt,
			&i.CategoryName,
			&i.CategoryColor,
			&i.LedgerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalSpentBetween = `-- name: TotalSpentBetween :one
SELECT CAST(COALESCE(SUM(amount), 0) AS INTEGER) FROM expenses
WHERE spent_at >= ? AND spent_at < ? AND deleted_at IS NULL
`

type TotalSpentBetweenParams struct {
	SpentAt   int64
	SpentAt_2 int64
}

func (q *Queries) TotalSpentBetween(ctx context.Context, arg TotalSpentBetweenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalSpentBetween, arg.SpentAt, arg.SpentAt_2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateExpense = `-- name: UpdateExpense :exec
UPDATE expenses
SET amount = ?, description = ?, notes = ?, spent_at = ?, category_id = ?, ledger_id = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateExpenseParams struct {
	Amount      int64
	Description string
	Notes       sql.NullString
	SpentAt     int64
	CategoryID  sql.NullInt64
	LedgerID    sql.NullInt64
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) error {
	_, err := q.db.ExecContext(ctx, updateExpense,
		arg.Amount,
		arg.Description,
		arg.Notes,
		arg.SpentAt,
		arg.CategoryID,
		arg.LedgerID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
