// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledgers.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearLedgerOnExpenses = `-- name: ClearLedgerOnExpenses :exec
UPDATE expenses SET ledger_id = NULL, updated_at = ? WHERE ledger_id = ?
`

type ClearLedgerOnExpensesParams struct {
	UpdatedAt int64
	LedgerID  sql.NullInt64
}

func (q *Queries) ClearLedgerOnExpenses(ctx context.Context, arg ClearLedgerOnExpensesParams) error {
	_, err := q.db.ExecContext(ctx, clearLedgerOnExpenses, arg.UpdatedAt, arg.LedgerID)
	return err
}

const createLedger = `-- name: CreateLedger :one
INSERT INTO ledgers (name, description, budget_amount, start_date, end_date, is_archived, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 0, ?, ?)
RETURNING id
`

type CreateLedgerParams struct {
	Name         string
	Description  sql.NullString
	BudgetAmount sql.NullInt64
	StartDate    sql.NullInt64
	EndDate      sql.NullInt64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLedger,
		arg.Name,
		arg.Description,
		arg.BudgetAmount,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteLedger = `-- name: DeleteLedger :exec
DELETE FROM ledgers WHERE id = ?
`

func (q *Queries) DeleteLedger(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLedger, id)
	return err
}

const getLedger = `-- name: GetLedger :one
SELECT id, name, description, budget_amount, start_date, end_date, is_archived, created_at, updated_at
FROM ledgers
WHERE id = ?
`

func (q *Queries) GetLedger(ctx context.Context, id int64) (Ledger, error) {
	row := q.db.QueryRowContext(ctx, getLedger, id)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BudgetAmount,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ledgerExpenseCount = `-- name: LedgerExpenseCount :one
SELECT COUNT(*) FROM expenses WHERE ledger_id = ? AND deleted_at IS NULL
`

// Counts active (non-trashed) expenses only.
func (q *Queries) LedgerExpenseCount(ctx context.Context, ledgerID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, ledgerExpenseCount, ledgerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ledgerTotalSpent = `-- name: LedgerTotalSpent :one
SELECT CAST(COALESCE(SUM(amount), 0) AS INTEGER) FROM expenses
WHERE ledger_id = ? AND deleted_at IS NULL
`

// Sums active (non-trashed) expenses only.
func (q *Queries) LedgerTotalSpent(ctx context.Context, ledgerID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, ledgerTotalSpent, ledgerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listActiveLedgers = `-- name: ListActiveLedgers :many
SELECT id, name, description, budget_amount, start_date, end_date, is_archived, created_at, updated_at
FROM ledgers
WHERE is_archived = 0
ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListActiveLedgers(ctx context.Context) ([]Ledger, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLedgers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ledger{}
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BudgetAmount,
			&i.StartDate,
			&i.EndDate,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllLedgers = `-- name: ListAllLedgers :many
SELECT id, name, description, budget_amount, start_date, end_date, is_archived, created_at, updated_at
FROM ledgers
ORDER BY is_archived, name COLLATE NOCASE
`

func (q *Queries) ListAllLedgers(ctx context.Context) ([]Ledger, error) {
	rows, err := q.db.QueryContext(ctx, listAllLedgers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ledger{}
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BudgetAmount,
			&i.StartDate,
			&i.EndDate,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedLedgers = `-- name: ListArchivedLedgers :many
SELECT id, name, description, budget_amount, start_date, end_date, is_archived, created_at, updated_at
FROM ledgers
WHERE is_archived = 1
ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListArchivedLedgers(ctx context.Context) ([]Ledger, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedLedgers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ledger{}
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BudgetAmount,
			&i.StartDate,
			&i.EndDate,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLedgerArchived = `-- name: SetLedgerArchived :exec
UPDATE ledgers
SET is_archived = ?, updated_at = ?
WHERE id = ?
`

type SetLedgerArchivedParams struct {
	IsArchived int64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) SetLedgerArchived(ctx context.Context, arg SetLedgerArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setLedgerArchived, arg.IsArchived, arg.UpdatedAt, arg.ID)
	return err
}

const updateLedger = `-- name: UpdateLedger :exec
UPDATE ledgers
SET name = ?, description = ?, budget_amount = ?, start_date = ?, end_date = ?, updated_at = ?
WHERE id = ?
`

type UpdateLedgerParams struct {
	Name         string
	Description  sql.NullString
	BudgetAmount sql.NullInt64
	StartDate    sql.NullInt64
	EndDate      sql.NullInt64
	UpdatedAt    int64
	ID           int64
}

func (q *Queries) UpdateLedger(ctx context.Context, arg UpdateLedgerParams) error {
	_, err := q.db.ExecContext(ctx, updateLedger,
		arg.Name,
		arg.Description,
		arg.BudgetAmount,
		arg.StartDate,
		arg.EndDate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
