// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_config.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteLLMConfig = `-- name: DeleteLLMConfig :exec
DELETE FROM llm_config WHERE id = 1
`

func (q *Queries) DeleteLLMConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteLLMConfig)
	return err
}

const getLLMConfig = `-- name: GetLLMConfig :one
SELECT id, provider, api_key_encrypted, text_model, enabled,
       last_test_at, last_test_success, last_test_error,
       created_at, updated_at
FROM llm_config
WHERE id = 1
`

func (q *Queries) GetLLMConfig(ctx context.Context) (LlmConfig, error) {
	row := q.db.QueryRowContext(ctx, getLLMConfig)
	var i LlmConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ApiKeyEncrypted,
		&i.TextModel,
		&i.Enabled,
		&i.LastTestAt,
		&i.LastTestSuccess,
		&i.LastTestError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLLMEnabled = `-- name: SetLLMEnabled :exec
UPDATE llm_config SET enabled = ?, updated_at = ? WHERE id = 1
`

type SetLLMEnabledParams struct {
	Enabled   int64
	UpdatedAt int64
}

func (q *Queries) SetLLMEnabled(ctx context.Context, arg SetLLMEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setLLMEnabled, arg.Enabled, arg.UpdatedAt)
	return err
}

const updateLLMTestResult = `-- name: UpdateLLMTestResult :exec
UPDATE llm_config
SET last_test_at      = ?,
    last_test_success = ?,
    last_test_error   = ?,
    updated_at        = ?
WHERE id = 1
`

type UpdateLLMTestResultParams struct {
	LastTestAt      sql.NullInt64
	LastTestSuccess int64
	LastTestError   sql.NullString
	UpdatedAt       int64
}

func (q *Queries) UpdateLLMTestResult(ctx context.Context, arg UpdateLLMTestResultParams) error {
	_, err := q.db.ExecContext(ctx, updateLLMTestResult,
		arg.LastTestAt,
		arg.LastTestSuccess,
		arg.LastTestError,
		arg.UpdatedAt,
	)
	return err
}

const upsertLLMConfig = `-- name: UpsertLLMConfig :exec
INSERT INTO llm_config (
    id, provider, api_key_encrypted, text_model, enabled,
    last_test_at, last_test_success, last_test_error, created_at, updated_at
) VALUES (1, ?, ?, ?, 0, NULL, 0, NULL, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    provider          = excluded.provider,
    api_key_encrypted = COALESCE(excluded.api_key_encrypted, llm_config.api_key_encrypted),
    text_model        = excluded.text_model,
    updated_at        = excluded.updated_at
`

type UpsertLLMConfigParams struct {
	Provider        string
	ApiKeyEncrypted sql.NullString
	TextModel       string
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) UpsertLLMConfig(ctx context.Context, arg UpsertLLMConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertLLMConfig,
		arg.Provider,
		arg.ApiKeyEncrypted,
		arg.TextModel,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
