// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_call_log.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteOldLLMCallLog = `-- name: DeleteOldLLMCallLog :execrows
DELETE FROM llm_call_log WHERE created_at < ?
`

func (q *Queries) DeleteOldLLMCallLog(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldLLMCallLog, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertLLMCallLog = `-- name: InsertLLMCallLog :exec
INSERT INTO llm_call_log (
    provider, model, purpose, latency_ms, input_tokens, output_tokens,
    success, error_message, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLLMCallLogParams struct {
	Provider     string
	Model        string
	Purpose      string
	LatencyMs    int64
	InputTokens  sql.NullInt64
	OutputTokens sql.NullInt64
	Success      int64
	ErrorMessage sql.NullString
	CreatedAt    int64
}

func (q *Queries) InsertLLMCallLog(ctx context.Context, arg InsertLLMCallLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLLMCallLog,
		arg.Provider,
		arg.Model,
		arg.Purpose,
		arg.LatencyMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Success,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	return err
}

const recentLLMCallLog = `-- name: RecentLLMCallLog :many
SELECT id, provider, model, purpose, latency_ms, input_tokens, output_tokens,
       success, error_message, created_at
FROM llm_call_log
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) RecentLLMCallLog(ctx context.Context, limit int64) ([]LlmCallLog, error) {
	rows, err := q.db.QueryContext(ctx, recentLLMCallLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmCallLog{}
	for rows.Next() {
		var i LlmCallLog
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Purpose,
			&i.LatencyMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Success,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
