// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AppState struct {
	Key   string
	Value string
}

type Category struct {
	ID         int64
	Name       string
	Color      string
	Icon       sql.NullString
	CreatedAt  int64
	IsArchived int64
}

type Expense struct {
	ID          int64
	Amount      int64
	Description string
	Notes       sql.NullString
	SpentAt     int64
	CategoryID  sql.NullInt64
	LedgerID    sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
	DeletedAt   sql.NullInt64
}

type Ledger struct {
	ID           int64
	Name         string
	Description  sql.NullString
	BudgetAmount sql.NullInt64
	StartDate    sql.NullInt64
	EndDate      sql.NullInt64
	IsArchived   int64
	CreatedAt    int64
	UpdatedAt    int64
}

type LlmCallLog struct {
	ID           int64
	Provider     string
	Model        string
	Purpose      string
	LatencyMs    int64
	InputTokens  sql.NullInt64
	OutputTokens sql.NullInt64
	Success      int64
	ErrorMessage sql.NullString
	CreatedAt    int64
}

type LlmConfig struct {
	ID              int64
	Provider        string
	ApiKeyEncrypted sql.NullString
	TextModel       string
	Enabled         int64
	LastTestAt      sql.NullInt64
	LastTestSuccess int64
	LastTestError   sql.NullString
	CreatedAt       int64
	UpdatedAt       int64
}

type Owner struct {
	ID                 int64
	Email              string
	PasswordHash       string
	DisplayName        string
	CurrencyCode       string
	CurrencySymbol     string
	Timezone           string
	CreatedAt          int64
	UpdatedAt          int64
	TrashRetentionDays int64
	DashboardUrl       string
}

type Session struct {
	ID        string
	CreatedAt int64
	ExpiresAt int64
	UserAgent sql.NullString
	IpAddress sql.NullString
}

type TelegramConfig struct {
	ID                int64
	BotTokenEncrypted string
	BotUsername       string
	ChatID            sql.NullInt64
	PairingCode       sql.NullString
	PairingExpiresAt  sql.NullInt64
	LastUpdateID      int64
	ActiveLedgerID    sql.NullInt64
	Enabled           int64
	CreatedAt         int64
	UpdatedAt         int64
}
