// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner.sql

package sqlcgen

import (
	"context"
)

const createOwner = `-- name: CreateOwner :exec
INSERT INTO owner (id, email, password_hash, display_name, currency_code, currency_symbol, timezone, created_at, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOwnerParams struct {
	Email          string
	PasswordHash   string
	DisplayName    string
	CurrencyCode   string
	CurrencySymbol string
	Timezone       string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) error {
	_, err := q.db.ExecContext(ctx, createOwner,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.CurrencyCode,
		arg.CurrencySymbol,
		arg.Timezone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOwner = `-- name: GetOwner :one
SELECT id, email, password_hash, display_name, currency_code, currency_symbol, timezone,
       created_at, updated_at, trash_retention_days, dashboard_url
FROM owner
WHERE id = 1
`

// Column order matches the table (post-migration: trash_retention_days
// and dashboard_url were ALTER-appended last) so sqlc emits the canonical
// Owner struct rather than a one-off GetOwnerRow.
func (q *Queries) GetOwner(ctx context.Context) (Owner, error) {
	row := q.db.QueryRowContext(ctx, getOwner)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CurrencyCode,
		&i.CurrencySymbol,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashRetentionDays,
		&i.DashboardUrl,
	)
	return i, err
}

const updateOwnerPassword = `-- name: UpdateOwnerPassword :exec
UPDATE owner
SET password_hash = ?, updated_at = ?
WHERE id = 1
`

type UpdateOwnerPasswordParams struct {
	PasswordHash string
	UpdatedAt    int64
}

func (q *Queries) UpdateOwnerPassword(ctx context.Context, arg UpdateOwnerPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateOwnerPassword, arg.PasswordHash, arg.UpdatedAt)
	return err
}

const updateOwnerPreferences = `-- name: UpdateOwnerPreferences :exec
UPDATE owner
SET currency_code = ?, currency_symbol = ?, timezone = ?, updated_at = ?
WHERE id = 1
`

type UpdateOwnerPreferencesParams struct {
	CurrencyCode   string
	CurrencySymbol string
	Timezone       string
	UpdatedAt      int64
}

func (q *Queries) UpdateOwnerPreferences(ctx context.Context, arg UpdateOwnerPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateOwnerPreferences,
		arg.CurrencyCode,
		arg.CurrencySymbol,
		arg.Timezone,
		arg.UpdatedAt,
	)
	return err
}

const updateOwnerProfile = `-- name: UpdateOwnerProfile :exec
UPDATE owner
SET email = ?, display_name = ?, updated_at = ?
WHERE id = 1
`

type UpdateOwnerProfileParams struct {
	Email       string
	DisplayName string
	UpdatedAt   int64
}

func (q *Queries) UpdateOwnerProfile(ctx context.Context, arg UpdateOwnerProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateOwnerProfile, arg.Email, arg.DisplayName, arg.UpdatedAt)
	return err
}

const updateOwnerTrashRetention = `-- name: UpdateOwnerTrashRetention :exec
UPDATE owner
SET trash_retention_days = ?, updated_at = ?
WHERE id = 1
`

type UpdateOwnerTrashRetentionParams struct {
	TrashRetentionDays int64
	UpdatedAt          int64
}

func (q *Queries) UpdateOwnerTrashRetention(ctx context.Context, arg UpdateOwnerTrashRetentionParams) error {
	_, err := q.db.ExecContext(ctx, updateOwnerTrashRetention, arg.TrashRetentionDays, arg.UpdatedAt)
	return err
}

const updateOwnerDashboardURL = `-- name: UpdateOwnerDashboardURL :exec
UPDATE owner
SET dashboard_url = ?, updated_at = ?
WHERE id = 1
`

type UpdateOwnerDashboardURLParams struct {
	DashboardUrl string
	UpdatedAt    int64
}

func (q *Queries) UpdateOwnerDashboardURL(ctx context.Context, arg UpdateOwnerDashboardURLParams) error {
	_, err := q.db.ExecContext(ctx, updateOwnerDashboardURL, arg.DashboardUrl, arg.UpdatedAt)
	return err
}
