// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Counts active (non-trashed) expenses only.
	CategoryExpenseCount(ctx context.Context, categoryID sql.NullInt64) (int64, error)
	ClearLedgerOnExpenses(ctx context.Context, arg ClearLedgerOnExpensesParams) error
	// Disconnecting a chat keeps the bot polling so the user can re-pair from a
	// different Telegram account. The "Disable" button (SetTelegramEnabled) is
	// the only path that flips enabled to 0.
	ClearTelegramChatID(ctx context.Context, updatedAt int64) error
	ClearTelegramPairingCode(ctx context.Context, updatedAt int64) error
	CountDeletedExpenses(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (int64, error)
	CreateLedger(ctx context.Context, arg CreateLedgerParams) (int64, error)
	CreateOwner(ctx context.Context, arg CreateOwnerParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DailySpendingBetween(ctx context.Context, arg DailySpendingBetweenParams) ([]DailySpendingBetweenRow, error)
	DailySpendingForLedger(ctx context.Context, ledgerID sql.NullInt64) ([]DailySpendingForLedgerRow, error)
	DeleteAllSessions(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error)
	DeleteLLMConfig(ctx context.Context) error
	DeleteLedger(ctx context.Context, id int64) error
	DeleteOldLLMCallLog(ctx context.Context, createdAt int64) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteTelegramConfig(ctx context.Context) error
	// Hard-deletes every currently soft-deleted row.
	EmptyTrash(ctx context.Context) (int64, error)
	GetAppState(ctx context.Context, key string) (string, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	// Trash-only fetch: returns the row regardless of state, used by Restore /
	// HardDelete handlers that need to read a soft-deleted row.
	GetDeletedExpense(ctx context.Context, id int64) (Expense, error)
	// Returns only active rows. Trash UI uses GetDeletedExpense for the trash side.
	GetExpense(ctx context.Context, id int64) (Expense, error)
	GetLLMConfig(ctx context.Context) (LlmConfig, error)
	GetLedger(ctx context.Context, id int64) (Ledger, error)
	// Column order matches the table (post-migration: trash_retention_days
	// was ALTER-appended last) so sqlc emits the canonical Owner struct
	// rather than a one-off GetOwnerRow.
	GetOwner(ctx context.Context) (Owner, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetTelegramConfig(ctx context.Context) (TelegramConfig, error)
	// Permanent delete. Used by the trash UI's "Delete forever" and by the
	// maintenance sweeper. Restricted to already-trashed rows so a stray call
	// can't bypass the trash.
	HardDeleteExpense(ctx context.Context, id int64) error
	InsertLLMCallLog(ctx context.Context, arg InsertLLMCallLogParams) error
	// Counts active (non-trashed) expenses only.
	LedgerExpenseCount(ctx context.Context, ledgerID sql.NullInt64) (int64, error)
	// Sums active (non-trashed) expenses only.
	LedgerTotalSpent(ctx context.Context, ledgerID sql.NullInt64) (int64, error)
	ListActiveCategories(ctx context.Context) ([]Category, error)
	ListActiveLedgers(ctx context.Context) ([]Ledger, error)
	ListAllCategories(ctx context.Context) ([]Category, error)
	ListAllLedgers(ctx context.Context) ([]Ledger, error)
	ListArchivedLedgers(ctx context.Context) ([]Ledger, error)
	// Trash listing, newest-deleted first.
	ListDeletedExpenses(ctx context.Context, arg ListDeletedExpensesParams) ([]ListDeletedExpensesRow, error)
	ListExpensesByLedger(ctx context.Context, ledgerID sql.NullInt64) ([]ListExpensesByLedgerRow, error)
	ListRecentExpenses(ctx context.Context, limit int64) ([]ListRecentExpensesRow, error)
	// Hard-deletes any soft-deleted rows older than the cutoff. Backs the
	// trash sweeper.
	PurgeOldDeletedExpenses(ctx context.Context, deletedAt sql.NullInt64) (int64, error)
	RecentLLMCallLog(ctx context.Context, limit int64) ([]LlmCallLog, error)
	// Brings a trashed row back. No-op for active rows.
	RestoreExpense(ctx context.Context, arg RestoreExpenseParams) error
	SetAppState(ctx context.Context, arg SetAppStateParams) error
	SetCategoryArchived(ctx context.Context, arg SetCategoryArchivedParams) error
	SetLLMEnabled(ctx context.Context, arg SetLLMEnabledParams) error
	SetLedgerArchived(ctx context.Context, arg SetLedgerArchivedParams) error
	SetTelegramActiveLedger(ctx context.Context, arg SetTelegramActiveLedgerParams) error
	SetTelegramChatID(ctx context.Context, arg SetTelegramChatIDParams) error
	SetTelegramEnabled(ctx context.Context, arg SetTelegramEnabledParams) error
	SetTelegramLastUpdateID(ctx context.Context, arg SetTelegramLastUpdateIDParams) error
	SetTelegramPairingCode(ctx context.Context, arg SetTelegramPairingCodeParams) error
	// Moves the row to trash. Idempotent: deleting an already-deleted row is a no-op.
	SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) error
	SpendingByCategoryBetween(ctx context.Context, arg SpendingByCategoryBetweenParams) ([]SpendingByCategoryBetweenRow, error)
	SpendingByCategoryForLedger(ctx context.Context, ledgerID sql.NullInt64) ([]SpendingByCategoryForLedgerRow, error)
	SpendingByLedgerBetween(ctx context.Context, arg SpendingByLedgerBetweenParams) ([]SpendingByLedgerBetweenRow, error)
	SummaryBetween(ctx context.Context, arg SummaryBetweenParams) (SummaryBetweenRow, error)
	TopExpensesBetween(ctx context.Context, arg TopExpensesBetweenParams) ([]TopExpensesBetweenRow, error)
	TotalSpentBetween(ctx context.Context, arg TotalSpentBetweenParams) (int64, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) error
	UpdateLLMTestResult(ctx context.Context, arg UpdateLLMTestResultParams) error
	UpdateLedger(ctx context.Context, arg UpdateLedgerParams) error
	UpdateOwnerPassword(ctx context.Context, arg UpdateOwnerPasswordParams) error
	UpdateOwnerPreferences(ctx context.Context, arg UpdateOwnerPreferencesParams) error
	UpdateOwnerProfile(ctx context.Context, arg UpdateOwnerProfileParams) error
	UpdateOwnerTrashRetention(ctx context.Context, arg UpdateOwnerTrashRetentionParams) error
	UpsertLLMConfig(ctx context.Context, arg UpsertLLMConfigParams) error
	// Saving a bot token enables polling immediately so the bot can RECEIVE the
	// /start <pairing_code> message that completes the pairing. Without this,
	// the supervisor would never start the bot and pairing could never finish.
	UpsertTelegramBot(ctx context.Context, arg UpsertTelegramBotParams) error
}

var _ Querier = (*Queries)(nil)
