// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_config.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearTelegramChatID = `-- name: ClearTelegramChatID :exec
UPDATE telegram_config
SET chat_id = NULL, active_ledger_id = NULL, updated_at = ?
WHERE id = 1
`

// Disconnecting a chat keeps the bot polling so the user can re-pair from a
// different Telegram account. The "Disable" button (SetTelegramEnabled) is
// the only path that flips enabled to 0.
func (q *Queries) ClearTelegramChatID(ctx context.Context, updatedAt int64) error {
	_, err := q.db.ExecContext(ctx, clearTelegramChatID, updatedAt)
	return err
}

const clearTelegramPairingCode = `-- name: ClearTelegramPairingCode :exec
UPDATE telegram_config
SET pairing_code = NULL, pairing_expires_at = NULL, updated_at = ?
WHERE id = 1
`

func (q *Queries) ClearTelegramPairingCode(ctx context.Context, updatedAt int64) error {
	_, err := q.db.ExecContext(ctx, clearTelegramPairingCode, updatedAt)
	return err
}

const deleteTelegramConfig = `-- name: DeleteTelegramConfig :exec
DELETE FROM telegram_config WHERE id = 1
`

func (q *Queries) DeleteTelegramConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTelegramConfig)
	return err
}

const getTelegramConfig = `-- name: GetTelegramConfig :one
SELECT id, bot_token_encrypted, bot_username, chat_id, pairing_code,
       pairing_expires_at, last_update_id, active_ledger_id, enabled,
       created_at, updated_at
FROM telegram_config
WHERE id = 1
`

func (q *Queries) GetTelegramConfig(ctx context.Context) (TelegramConfig, error) {
	row := q.db.QueryRowContext(ctx, getTelegramConfig)
	var i TelegramConfig
	err := row.Scan(
		&i.ID,
		&i.BotTokenEncrypted,
		&i.BotUsername,
		&i.ChatID,
		&i.PairingCode,
		&i.PairingExpiresAt,
		&i.LastUpdateID,
		&i.ActiveLedgerID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTelegramActiveLedger = `-- name: SetTelegramActiveLedger :exec
UPDATE telegram_config SET active_ledger_id = ?, updated_at = ? WHERE id = 1
`

type SetTelegramActiveLedgerParams struct {
	ActiveLedgerID sql.NullInt64
	UpdatedAt      int64
}

func (q *Queries) SetTelegramActiveLedger(ctx context.Context, arg SetTelegramActiveLedgerParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramActiveLedger, arg.ActiveLedgerID, arg.UpdatedAt)
	return err
}

const setTelegramChatID = `-- name: SetTelegramChatID :exec
UPDATE telegram_config
SET chat_id = ?, pairing_code = NULL, pairing_expires_at = NULL, enabled = 1, updated_at = ?
WHERE id = 1
`

type SetTelegramChatIDParams struct {
	ChatID    sql.NullInt64
	UpdatedAt int64
}

func (q *Queries) SetTelegramChatID(ctx context.Context, arg SetTelegramChatIDParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramChatID, arg.ChatID, arg.UpdatedAt)
	return err
}

const setTelegramEnabled = `-- name: SetTelegramEnabled :exec
UPDATE telegram_config SET enabled = ?, updated_at = ? WHERE id = 1
`

type SetTelegramEnabledParams struct {
	Enabled   int64
	UpdatedAt int64
}

func (q *Queries) SetTelegramEnabled(ctx context.Context, arg SetTelegramEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramEnabled, arg.Enabled, arg.UpdatedAt)
	return err
}

const setTelegramLastUpdateID = `-- name: SetTelegramLastUpdateID :exec
UPDATE telegram_config SET last_update_id = ?, updated_at = ? WHERE id = 1
`

type SetTelegramLastUpdateIDParams struct {
	LastUpdateID int64
	UpdatedAt    int64
}

func (q *Queries) SetTelegramLastUpdateID(ctx context.Context, arg SetTelegramLastUpdateIDParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramLastUpdateID, arg.LastUpdateID, arg.UpdatedAt)
	return err
}

const setTelegramPairingCode = `-- name: SetTelegramPairingCode :exec
UPDATE telegram_config
SET pairing_code = ?, pairing_expires_at = ?, updated_at = ?
WHERE id = 1
`

type SetTelegramPairingCodeParams struct {
	PairingCode      sql.NullString
	PairingExpiresAt sql.NullInt64
	UpdatedAt        int64
}

func (q *Queries) SetTelegramPairingCode(ctx context.Context, arg SetTelegramPairingCodeParams) error {
	_, err := q.db.ExecContext(ctx, setTelegramPairingCode, arg.PairingCode, arg.PairingExpiresAt, arg.UpdatedAt)
	return err
}

const upsertTelegramBot = `-- name: UpsertTelegramBot :exec
INSERT INTO telegram_config (
    id, bot_token_encrypted, bot_username, chat_id, pairing_code,
    pairing_expires_at, last_update_id, active_ledger_id, enabled,
    created_at, updated_at
) VALUES (1, ?, ?, NULL, NULL, NULL, 0, NULL, 1, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    bot_token_encrypted = excluded.bot_token_encrypted,
    bot_username        = excluded.bot_username,
    chat_id             = NULL,
    pairing_code        = NULL,
    pairing_expires_at  = NULL,
    last_update_id      = 0,
    active_ledger_id    = NULL,
    enabled             = 1,
    updated_at          = excluded.updated_at
`

type UpsertTelegramBotParams struct {
	BotTokenEncrypted string
	BotUsername       string
	CreatedAt         int64
	UpdatedAt         int64
}

// Saving a bot token enables polling immediately so the bot can RECEIVE the
// /start <pairing_code> message that completes the pairing. Without this,
// the supervisor would never start the bot and pairing could never finish.
func (q *Queries) UpsertTelegramBot(ctx context.Context, arg UpsertTelegramBotParams) error {
	_, err := q.db.ExecContext(ctx, upsertTelegramBot,
		arg.BotTokenEncrypted,
		arg.BotUsername,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
